package madlibs;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * Implements GUI components using Swing library.
 * Containing a button, a text input box, a text box (pop-up menu), and a text area.  
 */
public class UserInterface extends JPanel implements ActionListener {

    private JTextArea text; // a message will be posted to this text area
                            // each time an event is generated by some
                            // user action
    
    private JComboBox<String> combobox; // The pop-up menu.

    /**
     * This constructor adds several GUI components to the panel and listens
     * for action events from some of them.
     */
    public UserInterface() {

        setBorder(BorderFactory.createLineBorder(Color.GRAY, 3));
        setBackground(Color.WHITE);

        setLayout(new GridLayout(1, 2, 3, 3));
            // places the text area in the right half of the
            // panel. Each line contains a component and
            // a label for that component.

        text = new JTextArea();
        text.setEditable(false);
        text.setMargin(new Insets(4, 4, 4, 4));
        JPanel card1 = new JPanel();
        card1.setLayout(new GridLayout(4, 2, 3, 10));
        card1.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));
        add(card1);
        add(new JScrollPane(text));

        JLabel lab = new JLabel("Push Button:   ", JLabel.RIGHT);
        card1.add(lab);
        JButton b = new JButton("Click the button");
        b.addActionListener(this);
        card1.add(b);

        lab = new JLabel("Checkbox:   ", JLabel.RIGHT);
        card1.add(lab);
        JCheckBox c = new JCheckBox("Click the checkbox");
        c.addActionListener(this);
        card1.add(c);

        // Can be used during game to enter word
        lab = new JLabel("Text Field:   ", JLabel.RIGHT);
        card1.add(lab);
        JTextField t = new JTextField("Enter text here.");
        t.addActionListener(this);
        card1.add(t);

        lab = new JLabel("Pop-up Menu:   ", JLabel.RIGHT);
        card1.add(lab);
        combobox = new JComboBox<String>();
        combobox.addItem("Option 1");
        combobox.addItem("Option 2");
        combobox.addItem("Option 3");
        combobox.addItem("Option 4");
        combobox.addActionListener(this);
        card1.add(combobox);

    }
    // end of constructor

    
    private void post(String message) { // add a message and line feed to the text
        text.append(message + "\n\n");
    }

    /**
     * Respond to an ActionEvent from one of the GUI components in the panel.
     * In each case, a message about the event is posted to the text area.
     * This method is part of the ActionListener interface.
     */
    public void actionPerformed(ActionEvent evt) {
        Object target = evt.getSource(); // component that produced this event
        if (target instanceof JButton) {
            post("Button was clicked.");
        } else if (target instanceof JTextField) {
            post("Pressed return in TextField\nwith contents:\n    "
                    + evt.getActionCommand());
        } else if (target instanceof JCheckBox) {
            if (((JCheckBox) target).isSelected())
                post("Checkbox was turned on.");
            else
                post("Checkbox was turned off.");
        } else if (target == combobox) {
            Object item = combobox.getSelectedItem();
            post("Item \"" + item + "\" selected\nfrom pop-up menu.");
        }
    }
    
  //-----------------------------------------------------------------------------------

    /**
     * Main method 
     * creates a window containing a panel of type UserInterface.
     */
    public static void main(String[] args) {
        JFrame window = new JFrame("Mad Lib Game");
        window.setContentPane(new UserInterface());
        window.pack();
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setResizable(false);
        window.setLocation(150,100);
        window.setVisible(true);
    }



}


